services:
  kai-server:
    build: ./server
    image: kai-server:cloud
    ports:
      - "8000:8000"
    environment:
      GROQ_API_KEY: ${GROQ_API_KEY}
      GROQ_MODEL: ${GROQ_MODEL:-llama3-70b-8192}
    env_file:
      - .env
    restart: unless-stopped
